on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v3

      - name: Building web app
        uses: azure/appservice-build@v2

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{secrets.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.AZURE_WEB_APP_PUBLISH_PROFILE}}